### ISSUE TITLE
add version tag for redis

### ISSUE THREAD

**Issue by larrycai** [ArchCI/demo#1]
In demo command for starting redis, there is no version tag mentioned

```
docker run -d -p 6379:6379 redis
```
1. there are 2 major release for redis, 2 & 3, will be good to state it clearly
2. it will cause download extra images (I guess it will download all)

**Comment by tobegit3hub** [comment]
Adding the stable version of redis is meaningful and makes sure all my components will work.

Currently if you `docker pull redis`, it just pull the latest version of redis, not all. Anyway, I think we should add the specified version for all our dependencies.

**Comment by tobegit3hub** [comment]
Fix by https://github.com/ArchCI/demo/pull/2 and thanks @larrycai  :smiley:
